# Generated by Django 5.1.6 on 2025-02-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='grocery_data.grocery')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('grocery', 'date')},
            },
        ),
    ]
